### ISSUE TITLE
Bloomberg 

### ISSUE THREAD

**Issue by zawsq** [e7p/unscrambler#1]
Do this work on bloomberg and nytimes?

**Comment by e7p** [comment]
The script could work in situations where a blur is applied to the text and the text behind that blur is scrambled (and not based on random characters).

For Bloomberg, the text fades away, and thus there is no "dummy text" below, it is just missing there, so no way to get the full text.

For Nytimes, I didn't come across any paywall yet. If you could send a specific URL which definitely has a paywall, I could take a look into it.

**Comment by zawsq** [comment]
https://nytimes.com
https://www.wsj.com


I found a way on bloomberg by changing link on bloomberg
For example 
https://www.bloomberg.com/news/articles/2022-02-02/treasury-cuts-quarterly-sale-of-long-term-debt-as-spending-slows?srnd=markets-vp

Changing it to
https://www.bloomberg.com./news/articles/_______
With a (.com.) Works in incognito

**Comment by e7p** [comment]
For the wall street journal it is the same as with bloomberg. Still no luck finding a paywall on Nytimes.

I rather doubt that the dot after a domain name has any influence on implemented paywalls, but if it works for you, well...

I think I'll better gonna close this down as actually all of your suggestions have nothing to do with unscrambling scrambled text.
